Change license to MIT
arshadkazmi42/first-issues pull request #101
Opened 2022-09-21 23:14 UTC by AregPrograms

Fixes issue #100 

I know that the decision is not final. But I just made a PR so when everything is ready @arshadkazmi42 can quickly make the change.

2022-12-05 19:51 UTC, patel-aum approved these changes

2023-03-31 18:38 UTC, arshadkazmi42 requested changes
Sorry for the late review.

I have added a small change request, Once that is fixed we can get this merged

2023-03-31 18:38 UTC, arshadkazmi42 commented on LICENSE
> +Copyright 2015 First Issues
Can you add `MIT License` at the top. Similar to this [LICENSE](https://github.com/arshadkazmi42/currency-symbols/blob/master/LICENSE)

2023-04-08 19:17 UTC, arshadkazmi42 commented
@AregPrograms Are you working on this?

2023-04-16 12:46 UTC, arshadkazmi42 commented
Since there has been no updates closing this.

2023-04-16 12:46 UTC, closed without merging