Update README.md
arshadkazmi42/first-issues pull request #107
Opened 2023-01-04 11:19 UTC by Malavi1

I make an updated README file with added emoji reactions

2023-01-04 11:44 UTC, arshadkazmi42 requested changes
I think we should keep emojis only in the titles. Including emojis in the text is making it look cluttered.

But I like the emojis in the title.

Can you remove other emojis and keep the ones with the titles. Also I have added few review comments about spacing

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +## Troubleshooting😵
```suggestion
## Troubleshooting 😵
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +Read our how to use guide 👉[here](HOW_TO_USE.md).
```suggestion
Read our how to use guide [here](HOW_TO_USE.md).
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +Seeing any errors while running the bot? Check out the 🤠[Troubleshooting Guide](TROUBLESHOOTING.md).
```suggestion
Seeing any errors while running the bot? Check out the [Troubleshooting Guide](TROUBLESHOOTING.md).
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +If your problem is not present there,🧐 then go ahead and create an🤩 [issue](https://github.com/arshadkazmi42/first-issues/issues/new)
```suggestion
If your problem is not present there, then go ahead and create an [issue](https://github.com/arshadkazmi42/first-issues/issues/new)
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +- If you have got any suggestions, drop your suggestions😇 [here](https://github.com/arshadkazmi42/first-issues/issues/new).
```suggestion
- If you have got any suggestions, drop your suggestions [here](https://github.com/arshadkazmi42/first-issues/issues/new).
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +Read our Contribution guide 🤓 [here](Contribution.md).
```suggestion
Read our Contribution guide [here](Contribution.md).
```

2023-01-04 11:44 UTC, arshadkazmi42 commented on README.md
> +## Sponsors🥳
```suggestion
## Sponsors 🥳
```

2023-01-04 13:47 UTC, Malavi1 commented
That is also fine !! I remake this by placing emojis in the titles

2023-01-04 14:58 UTC, arshadkazmi42 commented
@Malavi1 These emojis looks good. You can update this PR by editing files [here](https://github.com/arshadkazmi42/first-issues/pull/107/files)

You can make the changes for the review comment I have added. Once those are done we can merge this pull request

2023-01-04 15:40 UTC, Malavi1 commented
In addition to the requested changes I replaced a few things also ! if  you thing good then continue otherwise I also ready to make changes 


thankyou !!!

2023-01-04 23:23 UTC, arshadkazmi42 approved these changes
Looks good. Thanks

2023-01-04 23:25 UTC, merged

2023-01-06 05:33 UTC, Malavi1 commented
My pleasure !!!